export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const CHANGE_FAVORITE_STATUS = "CHANGE_FAVORITE_STATUS";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
export const SORT_BY_PARAM = "SORT_BY_PARAM";
