export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ADD_ITEM_TO_FAVORITES = "ADD_ITEM_TO_FAVORITES";
export const FILTER_BY_CATEGORY = "FILTER_BY_CATEGORY";
export const FILTER_BY_PRICE = "FILTER_BY_PRICE";
